export const MFD = "МРД"
export const IMPORTANT_FRIDAY = "ВАЖНАЯ ПЯТНИЦА"
export const RUS_HELPS_CO = "РОС.ПОМОЩЬ"
export const FNS = "БАС"
export const ACCOUNTANT_SELF = "САМ"
export const ACCOUNTANT_OUTSOURCE = "АУТСОРСИНГ"
export const BOOKKEEPER = "БУХГАЛТЕР"
export const ALIEN = "ГОТОВАЯ КОФЕЙНЯ"
export const FRANCHISE = "ФРАНШИЗА"
export const FROM_NOTHING = "ВСЕ С НУЛЯ"
export const BAKANALITIKA = "БАКАНАЛИТИКА"
export const PERSONAL_ANALISYS = "ЛИЧНЫЙ АНАЛИЗ"
export const RENT_EQUIPMENT = "АРЕНДА ОБОРУДОВАНИЯ"
export const BUY_EQUIPMENT = "ПОКУПКА ОБОРУДОВАНИЯ"
export const SEARCH_WITH_FRIENDSHELP = "ПОИСК ЧЕРЕЗ ДРУЗЕЙ"
export const SEARCHING_CANDIDATE = "НАЙТИ КАДР"
export const WHOLESALE_BASE = "ОПТОВАЯ БАЗА"
export const DARKSTORE = "DARKSTORE"
export const PERSONAL_DISTRIBUTOR = "ЛИЧНЫЙ ПОСТАВЩИК"
export const PERMISSION_1 = "РАЗРЕШЕНИЕ 1"
export const PERMISSION_2 = "РАЗРЕШЕНИЕ 2"
export const RENT_AGENCY = "АГЕНСТВО НЕДВИЖИМОСТИ"
export const BY_YOURSELF = "САМОСТОЯТЕЛЬНО"
export const SMALL_DISTRICT = "МАЛЕНЬКОЕ В СПАЛЬНОМ РАЙОНЕ"
export const SMALL_IN_RED_LINE = "МАЛЕНЬКОЕ НА КРАСНОЙ ЛИНИИ"
export const BIG_IN_RED_LINE = "БОЛЬШОЕ НА КРАСНОЙ ЛИНИИ"
export const ECONOMY = "ЭКОНОМ"
export const STANDART = "СТАНДАРТ"
export const VIP = "ВИП"

/** Константы для редюсера */
export const UPDATE_ROUND = "UPDATE_ROUND"
export const FILTER_ACTIONS = "FILTER_ACTIONS"
export const UPDATE_VISITORS = "UPDATE_VISITORS"
export const SET_AMORTIZATION = "SET_AMORTIZATION"
export const UPDATE_CR = "UPDATE_CR"
export const UPDATE_AVPRICE = "UPDATE_AVPRICE"
export const UPDATE_AVPAYMENT = "UPDATE_AVPAYMENT"
export const UPDATE_ACTION_COST = "UPDATE_ACTION_COST"
export const UPDATE_COMMISSIONS = "UPDATE_COMMISSIONS"
export const UPDATE_SALARY = "UPDATE_SALARY"
export const UPDATE_DIALOG_TEXT = "UPDATE_DIALOG_TEXT"
export const UPDATE_RENT = "UPDATE_RENT"
export const ARRIVED_GEESE = "ARRIVED_GEESE"
export const SET_TABLE_DATA = "SET_TABLE_DATA"
export const SHOW_TABLE = "SHOW_TABLE"

export const NEXT_STEP = "NEXT_STEP"
export const TOGGLE_GAME = "TOGGLE_GAME"
export const SET_CASH = "SET_CASH"
export const CHANGE_CASH = "CHANGE_CASH" // расходы
export const SET_GOOSE_TEXT = "SET_GOOSE_TEXT"
export const SET_NAME = "SET_NAME"

/** Константы для действий пользователя */

export const EXPEND_ASSORTMENT = "Расширить ассортимент"
export const INSERT_DELIVERY = "Подключить доставку"
export const EXPEND_STAFF = "Увеличить штат сотрудников"
export const ORDER_OFF_LINE_PROMO = "Заказать рекламу off-line"
export const ORDER_ON_LINE_PROMO = "Заказать рекламу on-line"
export const LAUNCH_LOYALTY_PROGRAM = "Запустить программу лояльности"
export const REFRESH_MENU = "Обновить меню"
export const DECORATE_HALL = "Украсить зал к новому году"
export const UPGRADE_RULES_OF_DRINK = "Улучшить правила подачи напитков"
export const CREATE_COMBO_MENU = "Разработать комбо предложение кофе"
export const CREATE_BRAND = "Разработать брендинг кафе"
export const DO_NOTHING = "Ничего не подключать"
